@base_url = {{dev_url}}
@api_key = 8b958b7ff05346f2bdb954781910055a

# @name Meals all search

GET {{base_url}}/recipes/complexSearch?apiKey={{api_key}}&query="pasta"
Content-Type: application/json
Accept: application/json

### 

# @name Menu get

GET {{base_url}}/food/menuItems/search?apiKey={{api_key}}&query="pasta"
Content-Type: application/json
Accept: application/json

### 